# How to use Deep Learning to predict The Definite Future with Feedforward Network
## Multistep Univariate Linear Perceptron
### Author : Mohamed JELIDI, Email : jelidi.mohamad@gmail.com

In practice, there is little difference to the MLP model in predicting a vector output that represents different output variables (as in the previous example) or a vector output that represents multiple time steps of one variable. Nevertheless, there are subtle and important differences in the way the training data is prepared. In this section, we will demonstrate the case of developing a multi-step forecast model using a vector model. Before we look at the specifics of the model, let’s first look at the preparation of data for multi-step forecasting.

## Preprocessing data

In [0]:
# multi-step data preparation
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
  X, y = list(), list()
  for i in range(len(sequence)):
    # find the end of this pattern
    end_ix = i + n_steps_in
    out_end_ix = end_ix + n_steps_out
    # check if we are beyond the sequence
    if out_end_ix > len(sequence):
      break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)
# define input sequence
raw_seq = [100, 200, 300, 400, 500, 600, 700, 800, 900]
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# summarize the data
for i in range(len(X)):
  print(X[i], y[i])

[100 200 300] [400 500]
[200 300 400] [500 600]
[300 400 500] [600 700]
[400 500 600] [700 800]
[500 600 700] [800 900]


In [0]:
# define input sequence
raw_seq = [1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1]
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# summarize the data
for i in range(len(X)):
  print(X[i], y[i])

[1 1 1] [2 2]
[1 1 2] [2 2]
[1 2 2] [2 1]
[2 2 2] [1 2]
[2 2 1] [2 1]
[2 1 2] [1 1]
[1 2 1] [1 1]
[2 1 1] [1 1]
[1 1 1] [1 2]
[1 1 1] [2 2]
[1 1 2] [2 2]
[1 2 2] [2 1]
[2 2 2] [1 2]
[2 2 1] [2 1]
[2 1 2] [1 1]
[1 2 1] [1 1]
[2 1 1] [1 1]
[1 1 1] [1 2]
[1 1 1] [2 2]
[1 1 2] [2 2]
[1 2 2] [2 1]
[2 2 2] [1 2]
[2 2 1] [2 1]


# MLP Model

In [0]:
# define model
model = Sequential()
model.add(Dense(100, activation='relu', input_dim=n_steps_in))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')

In [0]:
# fitting the model
model.fit(X, y, epochs=2000, verbose=0)

In [0]:
# demonstrate prediction
x_input = array([0, 2, 2])
x_input = x_input.reshape((1, n_steps_in))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[2.947235   0.14778869]]


In [0]:
# Automate prediction to observe results
print('Predicted\t\t','Actuals')
for i in range(len(X)):
  x_input = array(X[i]).reshape((1, n_steps_in))
  yhat = model.predict(x_input, verbose=0)
  print(yhat,'\t\t', y[i])

Predicted		 Actuals
[[1.5994239 1.999349 ]] 		 [2 2]
[[2.0038064 1.9980189]] 		 [2 2]
[[1.9948318 1.003254 ]] 		 [2 1]
[[1.0070384 1.9956039]] 		 [1 2]
[[1.9931372 1.0028354]] 		 [2 1]
[[0.98906237 1.0053579 ]] 		 [1 1]
[[1.0068331 0.9982864]] 		 [1 1]
[[1.0093566 0.9969254]] 		 [1 1]
[[1.5994239 1.999349 ]] 		 [1 2]
[[1.5994239 1.999349 ]] 		 [2 2]
[[2.0038064 1.9980189]] 		 [2 2]
[[1.9948318 1.003254 ]] 		 [2 1]
[[1.0070384 1.9956039]] 		 [1 2]
[[1.9931372 1.0028354]] 		 [2 1]
[[0.98906237 1.0053579 ]] 		 [1 1]
[[1.0068331 0.9982864]] 		 [1 1]
[[1.0093566 0.9969254]] 		 [1 1]
[[1.5994239 1.999349 ]] 		 [1 2]
[[1.5994239 1.999349 ]] 		 [2 2]
[[2.0038064 1.9980189]] 		 [2 2]
[[1.9948318 1.003254 ]] 		 [2 1]
[[1.0070384 1.9956039]] 		 [1 2]
[[1.9931372 1.0028354]] 		 [2 1]


**Note:** Given the stochastic nature of this algorithm, your  results may vary.